name: Publish Package

on:
  release:
    types:
    - published

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.

    - name: Run xunit tests
      run: dotnet test ./src/

    - name: Build with dotnet
      run: dotnet pack --configuration Release --output nupkgs ./src/Upstream.Testing

  publish:
    name: Publish package
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.

    - name: Create NuGet package
      run: |
        REF="${{ github.ref }}"
        FILTER="refs/tags/v"
        export VERSION="${REF//$FILTER}"
        echo "Building Upstream.Testing v${VERSION}"
        dotnet pack --configuration Release --output nupkgs ./src/Upstream.Testing

    - name: Publish NuGet package ${{ github.ref }}
      run: |
        PACKAGE=$(find ./nupkgs/ -name "Upstream.Testing.*.nupkg")
        dotnet nuget push $PACKAGE -k ${{ secrets.NuGetApiKey }} -s https://api.nuget.org/v3/index.json
