name: Run Tests

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.

    - name: Run xunit tests
      run: dotnet test ./src/
