name: Run Tests

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1

    - name: Run xunit tests
      run: dotnet test ./src/
